build: Add dependency on proto_generated_headers for proto_generated_objects
In case of high j value to make, occasionally headers
required to compile the proto sources are not being
generated before hand and causing below compilation
failure:

hardware/ril/mock-ril/src/proto/ctrl.pb.h:26:52:
error: hardware/ril/mock-ril/src/proto/ril.pb.h: No such file or directory

This is due to ctrl.proto is importing ril.proto package
and dependency is only set on the ctrl header generated,
but, not on ril header.

CRs-fixed: 351094
(cherry picked from commit 0907ef848da4497ce85569ebbca683e355dfbcbf)

Change-Id: I1eb8f23e417fd4959719a1f8110ddd1d53a3693c